x-customizable-image: &customizable_image
  image: frappe/erpnext:v15.91.1
  pull_policy: always

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: [*depends_on_configurator, *customizable_image]
  volumes:
    - sites:/home/frappe/frappe-bench/sites

services:
  configurator:
    <<: *customizable_image
    command: >
      bash -c "ls -1 apps > sites/apps.txt &&
               bench set-config -g db_host db &&
               bench set-config -gp db_port 3306 &&
               bench set-config -g redis_cache 'redis://redis-cache:6379' &&
               bench set-config -g redis_queue 'redis://redis-queue:6379' &&
               bench set-config -g redis_socketio 'redis://redis-queue:6379' &&
               bench set-config -gp socketio_port 9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started

  create-site:
    <<: *customizable_image
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | python3 -c "import sys, json; cfg = json.load(sys.stdin); print(cfg.get('db_host', ''))"` ]];
        do
          echo "Waiting for configurator...";
          sleep 5;
          if (( `date +%s`-start > 120 )); then echo "Could not find common_site_config.json with db_host"; exit 1; fi;
        done;
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-password=admin --install-app erpnext --set-default frontend;
    depends_on:
      configurator:
        condition: service_completed_successfully

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  backend:
    <<: *backend_defaults

  frontend:
    <<: [*depends_on_configurator, *customizable_image]
    command: nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "7777:8080"

  websocket:
    <<: [*depends_on_configurator, *customizable_image]
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    <<: *backend_defaults
    command: bench worker --queue short,default

  queue-long:
    <<: *backend_defaults
    command: bench worker --queue long

  scheduler:
    <<: *backend_defaults
    command: bench schedule

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  logs:
